[package]
org = "ballroom"
name = "executor_service"
version = "0.1.0"
distribution = "2201.5.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballroom"
name = "data_model"
version = "0.1.0"
repository="local"