rabbitmqHost = "rabbitmq"
rabbitmqPort = 5672
rabbitmqUser = "guest"
rabbitmqPassword = "guest"


[ballroom.entities]
host = "mysql"
port = 3306
user = "ballroom_sql"
password = "ballroomadmin123"
database = "ballroomdb"
connectionOptions = {ssl = {allowPublicKeyRetrieval = true}}
