orgName = <<ORG_NAME>> 
clientId = <<CLIENT_ID>> 
clientSecret = <<CLIENT_SECRET>>
adminGroupId = <<ADMIN_GROUP_ID>>
contestantGroupId = <<CONTESTANT_GROUP_ID>>

[ballroom.entities]
host = "mysql"
port = 3306
user = "ballroom_sql"
password = "ballroomadmin123"
database = "ballroomdb"
connectionOptions = {ssl = {allowPublicKeyRetrieval = true}}
