[container.image]
name = "bff-service"
repository = "swr.ap-southeast-1.myhuaweicloud.com/ballroom"
tag = "latest"

[cloud.deployment]
internal_domain_name="bff-service"
min_memory="256Mi"
max_memory="512Mi"
min_cpu="250m"
max_cpu="1000m"

[cloud.deployment.autoscaling]
min_replicas=1
max_replicas=1

[[cloud.config.files]]
file="./k8s/Config.toml"
name="bff-config" 

[settings]
thinJar=false
