[package]
distribution = "2201.5.0"
export = ["ballroom.data_model.registry", "ballroom.data_model"]
name = "ballroom.data_model"
org = "ballroom"
version = "0.1.0"

[build-options]
observabilityIncluded = true
