rabbitmqHost = "rabbitmq-service"
rabbitmqPort = 5672
rabbitmqUser = "guest"
rabbitmqPassword = "guest"

[ballroom.entities]
host = "mysql-service"
port = 3306
user = "root"
password = "password"
database = "ballroomdb"
connectionOptions = {ssl = {allowPublicKeyRetrieval = true}}
