[package]
distribution = "2201.5.0"
name = "sts_service"
org = "ballroom"
version = "0.1.0"

[build-options]
observabilityIncluded = true

[[dependency]]
name = "data_model"
org = "ballroom"
repository = "local"
version = "0.1.0"

[[tool.openapi]]
id = "user-service"
file = "../user-service/openapi.yaml"
#package = "user-service"
#mode = "client" #optional - default is "client"
