[container.image]
name = "sts-service"
repository = "ballroom"
tag = "0.1.0"

[[container.copy.files]]
sourceFile = "./certificates/jwt/server.key"
target = "./certificates/jwt/server.key"

[[container.copy.files]]
sourceFile = "./certificates/jwt/server.crt"
target = "./certificates/jwt/server.crt"

[[container.copy.files]]
sourceFile="./Config.toml"
target="./Config.toml"

