[package]
distribution = "2201.5.0"
name = "user_service"
org = "ballroom"
version = "0.1.0"

[build-options]
observabilityIncluded = true

[[dependency]]
name = "data_model"
org = "ballroom"
repository = "local"
version = "0.1.0"
